name: Sonarcloud

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: ls; 
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        SONAR_TOKEN: ${ secrets.SONAR_TOKEN }
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
