name: Swift

on: [push]

jobs:
  build:

    runs-on: macos
    
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone X', 'platform=tvOS Simulator,OS=13.3,name=Apple TV 4K']
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage --show-codecov-path
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
